"""Seed the model library with real geometry.

Companion to `seed_materials.py`. Every model here is a **genuine binary STL**,
generated by this script and pushed through `ModelLibrary.ingest` — the same path
a customer upload takes — so the triangle count, bounding box, volume and
watertightness on each card are measured by `analyse_stl` rather than typed in.

That matters more than it sounds. The catalogue's whole claim is that its numbers
are facts; seeding it with invented dimensions would make the first thing anyone
sees a demonstration of the opposite.

    cd backend && .venv/Scripts/python scripts/seed_catalog.py

Idempotent: content-addressed storage means re-running costs one hash per model
and writes nothing new.
"""

from __future__ import annotations

import asyncio
import struct
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

import printorian.models  # noqa: F401 - registers every table on the metadata
from printorian.contexts.catalog.assets import ModelLibrary
from printorian.contexts.catalog.catalogue import (
    CatalogModel,
    CatalogModelMaterial,
    ModelCategory,
    Suitability,
    size_class_of,
)
from printorian.contexts.catalog.preview import outline
from printorian.core.clock import SystemClock
from printorian.core.config import Settings
from printorian.core.ids import new_id
from printorian.core.storage import FilesystemObjectStore
from scripts._geometry import Point, Tri, extrude

# --------------------------------------------------------------- geometry


def _l_profile(length: float, height: float, thickness: float) -> list[Point]:
    """An L, as a closed polygon. The bracket's cross-section."""
    return [
        (0.0, 0.0),
        (length, 0.0),
        (length, thickness),
        (thickness, thickness),
        (thickness, height),
        (0.0, height),
    ]


def _u_profile(width: float, height: float, thickness: float) -> list[Point]:
    """A U — a tray seen end-on: floor with a wall at each side."""
    return [
        (0.0, 0.0),
        (width, 0.0),
        (width, height),
        (width - thickness, height),
        (width - thickness, thickness),
        (thickness, thickness),
        (thickness, height),
        (0.0, height),
    ]


def _stepped_profile(width: float, height: float, step: float) -> list[Point]:
    """A two-step outline, for the enclosure."""
    return [
        (0.0, 0.0),
        (width, 0.0),
        (width, height - step),
        (width - step, height - step),
        (width - step, height),
        (0.0, height),
    ]


def _bracket() -> list[Tri]:
    """The kit's `BRACKET_V4`: an L-section, 64 mm deep.

    A real part rather than a cube — the 3D view exists to show the viewer works
    on geometry somebody would actually print.
    """
    return extrude(_l_profile(length=128.0, height=44.0, thickness=6.0), 64.0)


def _stepped_case() -> list[Tri]:
    """A stepped enclosure, standing in for a Raspberry Pi case."""
    return extrude(_stepped_profile(width=96.0, height=30.0, step=8.0), 62.0)


def _tray() -> list[Tri]:
    """A U-section tray."""
    return extrude(_u_profile(width=220.0, height=45.0, thickness=6.0), 140.0)


def _clip() -> list[Tri]:
    """A small cable clip: the same L, much smaller."""
    return extrude(_l_profile(length=24.0, height=8.0, thickness=3.0), 12.0)


def binary_stl(triangles: list[Tri], header: str) -> bytes:
    """Write triangles as a binary STL.

    Normals are written as zero, which the format permits and every reader
    tolerates: the winding above is the authority on facing, and a stored normal
    that disagreed with it would be a second source of truth for the same fact.
    """
    out = bytearray(header.encode("ascii", "replace")[:80].ljust(80, b"\0"))
    out += struct.pack("<I", len(triangles))
    for tri in triangles:
        out += struct.pack("<3f", 0.0, 0.0, 0.0)
        for vertex in tri:
            out += struct.pack("<3f", *vertex)
        out += struct.pack("<H", 0)
    return bytes(out)


# ------------------------------------------------------------------ models


@dataclass(frozen=True, slots=True)
class Seed:
    slug: str
    code: str
    title: str
    summary: str
    category: ModelCategory
    triangles: list[Tri]
    #: (code, suitability, note, recommended) — the kit's «Подходящие материалы»
    #: columns that are editorial. Δ price and stock are read from inventory.
    materials: tuple[tuple[str, str, str, bool], ...]
    #: difficulty, strength, accuracy, speed, supports, postprocessing — 0–10
    bars: tuple[int, int, int, int, int, int]
    multicolor: bool
    print_count: int
    rating: tuple[int, int]
    author: str
    #: Whether this one has been printed. Half the seeds have not, so the
    #: measured-versus-not distinction is visible on a fresh install.
    printed: bool


SEEDS: tuple[Seed, ...] = (
    Seed(
        "bracket-v4",
        "BRACKET_V4",
        "Кронштейн угловой V4",
        "Несущий кронштейн под нагрузку до 40 кг для наружного монтажа. Рёбра "
        "жёсткости рассчитаны под печать без поддержек в вертикальной ориентации — "
        "именно так он и печатается у нас.",
        ModelCategory.FUNCTIONAL,
        _bracket(),
        (
            ("petg", "excellent", "", True),
            ("asa", "excellent", "", False),
            ("pla", "limited", "Не для улицы", False),
        ),
        (6, 8, 7, 5, 1, 2),
        False,
        312,
        (48, 10),
        "Инженерная группа",
        True,
    ),
    Seed(
        "housing-pi5",
        "HOUSING_B",
        "Корпус для Raspberry Pi 5",
        "Двухсекционный корпус с вентиляционными окнами. Печатается без поддержек, "
        "крышка садится на защёлках.",
        ModelCategory.CASE,
        _stepped_case(),
        (("pla", "excellent", "", True), ("petg", "good", "", False)),
        (3, 5, 8, 6, 0, 3),
        False,
        164,
        (46, 10),
        "Инженерная группа",
        True,
    ),
    Seed(
        "tray-6",
        "TRAY_6",
        "Органайзер для стола, 6 ячеек",
        "Лоток с перегородками под мелкий крепёж. Габарит подобран под ящик стандартного стола.",
        ModelCategory.ORGANISER,
        _tray(),
        (("pla", "excellent", "", True), ("petg", "good", "", False)),
        (1, 4, 5, 8, 0, 1),
        False,
        238,
        (44, 10),
        "Сообщество",
        False,
    ),
    Seed(
        "clip-a",
        "CLIP_A",
        "Клипса кабельная",
        "Мелочь, которую заказывают тиражом. На столе помещается больше сотни за одну печать.",
        ModelCategory.FUNCTIONAL,
        _clip(),
        (("pla", "good", "", False), ("tpu", "excellent", "Гибкая посадка", True)),
        (1, 6, 6, 9, 0, 0),
        False,
        1840,
        (47, 10),
        "Сообщество",
        True,
    ),
)


async def main() -> None:
    settings = Settings()
    engine = create_async_engine(settings.database_url)
    factory = async_sessionmaker(engine, expire_on_commit=False)
    store = FilesystemObjectStore(settings.storage_root)
    clock = SystemClock()

    async with factory() as db:
        library = ModelLibrary(db, store, clock)
        for seed in SEEDS:
            if await db.scalar(select(CatalogModel).where(CatalogModel.slug == seed.slug)):
                print(f"  = {seed.slug} (already present)")
                continue

            # Through the real ingest path, so the geometry on the card is
            # measured by `analyse_stl` rather than asserted here.
            geometry = binary_stl(seed.triangles, f"printorian {seed.code}")
            asset = await library.ingest(geometry, filename=f"{seed.code.lower()}.stl")
            # The card's line drawing, projected from the same bytes — so the
            # grid shows the actual part rather than a placeholder cube.
            drawing = outline(geometry)

            difficulty, strength, accuracy, speed, supports, postprocessing = seed.bars
            model = CatalogModel(
                id=new_id(),
                slug=seed.slug,
                code=seed.code,
                title=seed.title,
                summary=seed.summary,
                category=seed.category,
                size_class=size_class_of(asset.width_mm, asset.depth_mm, asset.height_mm),
                difficulty=difficulty,
                strength=strength,
                accuracy=accuracy,
                speed=speed,
                supports=supports,
                postprocessing=postprocessing,
                author=seed.author,
                multicolor=seed.multicolor,
                tags=[],
                model_asset_id=asset.id,
                license="CC BY-NC",
                version="1.0",
                rating_sum=seed.rating[0],
                rating_count=seed.rating[1],
                print_count=seed.print_count,
                is_published=True,
                published_at=datetime(2026, 7, 12, tzinfo=UTC),
                preview=drawing,
                # Measured facts only for the ones marked printed. The others stay
                # null, which is what makes the storefront say so.
                last_printed_at=datetime(2026, 8, 9, tzinfo=UTC) if seed.printed else None,
                last_print_minutes=Decimal(141) if seed.printed else None,
                last_print_grams=(
                    (asset.volume_cm3 * Decimal("1.24")).quantize(Decimal("0.01"))
                    if seed.printed
                    else None
                ),
                last_price=Decimal(601) if seed.printed else None,
                last_printer_name="P-01" if seed.printed else "",
            )
            db.add(model)
            await db.flush()
            for code, suitability, note, recommended in seed.materials:
                db.add(
                    CatalogModelMaterial(
                        model_id=model.id,
                        material_code=code,
                        suitability=Suitability(suitability),
                        note=note,
                        is_recommended=recommended,
                    )
                )

            # ASCII only: this runs on a Windows console whose default code
            # page is cp1251, which cannot encode "×" — and a seed script that
            # crashes on its own progress line is worse than a plain one.
            print(
                f"  + {seed.slug}: {asset.triangle_count} triangles, "
                f"{asset.width_mm} x {asset.depth_mm} x {asset.height_mm} mm, "
                f"{asset.volume_cm3} cm3, "
                f"{'watertight' if asset.is_watertight else 'NOT WATERTIGHT'}"
            )
        await db.commit()

    await engine.dispose()
    print("done")


if __name__ == "__main__":
    asyncio.run(main())
