"""Reading a slicer's output.

Ported with the parser itself when ADR-0016 removed the desktop app. These numbers
become the truth an order is repriced against (ADR-0013), so the rule under test
throughout is: **when the file does not say, say nothing.** A wrong parse is worse
than no parse, because no parse asks the engineer to type it.
"""

from __future__ import annotations

import io
import zipfile
from decimal import Decimal
from pathlib import Path

import pytest

from printorian.contexts.catalog.plate_file import (
    SLICE_INFO,
    parse_duration,
    parse_filament_grams,
    parse_print_minutes,
    read_plate,
)

#: A real Bambu Studio project, committed at the backend root.
REAL_3MF = Path(__file__).resolve().parents[2] / "test.3mf"


def a_3mf(slice_info: str) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr(SLICE_INFO, slice_info)
    return buffer.getvalue()


SLICED = """<?xml version="1.0" encoding="UTF-8"?>
<config>
  <header><header_item key="X-BBL-Client-Type" value="slicer"/></header>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="prediction" value="4521"/>
    <metadata key="weight" value="27.15"/>
    <filament id="1" type="PLA" color="#000000" used_m="7.62" used_g="22.73"/>
    <filament id="2" type="PLA" color="#FFFFFF" used_m="1.44" used_g="4.42"/>
  </plate>
</config>
"""


# ------------------------------------------------------------------ durations


class TestParseDuration:
    def test_reads_the_shapes_slicers_write(self) -> None:
        assert parse_duration("1h 4m 30s") == 65
        assert parse_duration("64m") == 64
        assert parse_duration("2h") == 120

    def test_rounds_seconds_up(self) -> None:
        """A plate is never *less* work than the slicer said.

        Rounding a job's duration down is how a schedule quietly slips.
        """
        assert parse_duration("1m 1s") == 2

    def test_says_nothing_when_there_is_no_duration(self) -> None:
        assert parse_duration("unknown") is None
        assert parse_duration("") is None

    def test_does_not_read_milliseconds_as_minutes(self) -> None:
        assert parse_duration("500ms") is None


class TestParsePrintMinutes:
    def test_reads_a_prusaslicer_comment(self) -> None:
        assert parse_print_minutes("; estimated printing time (normal mode) = 1h 4m 30s") == 65

    def test_prefers_the_print_over_the_whole_job(self) -> None:
        """`total estimated time` includes preheating and calibration.

        Scheduling against it makes every job look longer than the bed is busy.
        """
        assert parse_print_minutes("; model printing time: 64m; total estimated time: 70m") == 64

    def test_says_nothing_when_the_file_never_does(self) -> None:
        assert parse_print_minutes("; generated by something") is None


class TestParseFilamentGrams:
    def test_keys_grams_by_slot(self) -> None:
        """Per slot, not a total.

        A multi-colour plate can exhaust one spool while the others are full, and
        the scheduler needs to know which.
        """
        assert parse_filament_grams("; filament used [g] = 17.3, 4.2") == {
            "0": Decimal("17.3"),
            "1": Decimal("4.2"),
        }

    def test_treats_a_single_total_as_slot_zero(self) -> None:
        assert parse_filament_grams("; total filament weight [g] : 17.3") == {"0": Decimal("17.3")}

    def test_drops_zero_and_unreadable_entries(self) -> None:
        assert parse_filament_grams("; filament used [g] = 17.3, 0, n/a") == {"0": Decimal("17.3")}

    def test_is_empty_when_the_file_never_says(self) -> None:
        assert parse_filament_grams("; nothing useful here") == {}


# ---------------------------------------------------------------- whole plates


class TestReadPlate:
    def test_is_parsed_only_when_both_numbers_were_found(self) -> None:
        both = read_plate(b"; estimated printing time = 64m\n; filament used [g] = 17.3")
        assert both.parsed

        time_only = read_plate(b"; estimated printing time = 64m")
        assert not time_only.parsed
        assert time_only.print_minutes == 64

    def test_reads_a_sliced_3mf(self) -> None:
        """The one thing this port gains from running on a server.

        The desktop app could not open the zip, so every uploaded 3MF came back
        unparsed and the engineer typed both numbers by hand.
        """
        numbers = read_plate(a_3mf(SLICED))

        assert numbers.parsed
        # 4521 seconds is 75.35 minutes, rounded up.
        assert numbers.print_minutes == 76
        # Bambu numbers filaments from 1; the API keys slots from 0.
        assert numbers.filament_grams == {"0": Decimal("22.73"), "1": Decimal("4.42")}

    @pytest.mark.skipif(not REAL_3MF.exists(), reason="sample project not present")
    def test_a_real_project_file_yields_nothing(self) -> None:
        """A project saved *before* slicing genuinely does not know the numbers.

        Its `slice_info.config` carries a header and no `<plate>`. That is not a
        damaged file and not an error — the honest answer is to report nothing and
        let the engineer type them.
        """
        numbers = read_plate(REAL_3MF.read_bytes())

        assert not numbers.parsed
        assert numbers.print_minutes is None
        assert numbers.filament_grams == {}

    def test_a_damaged_archive_reports_nothing_rather_than_raising(self) -> None:
        """An upload is attacker-reachable; a parse failure must not be a 500."""
        assert not read_plate(b"PK\x03\x04 truncated nonsense").parsed

    def test_an_archive_without_slice_info_reports_nothing(self) -> None:
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w") as archive:
            archive.writestr("3D/3dmodel.model", "<model/>")
        assert not read_plate(buffer.getvalue()).parsed

    def test_unreadable_xml_reports_nothing(self) -> None:
        assert not read_plate(a_3mf("<config><plate>")).parsed

    def test_a_plate_with_no_filament_is_not_parsed(self) -> None:
        """Time without grams is half an answer, and half is the dangerous half."""
        header_only = """<config><plate>
            <metadata key="prediction" value="600"/>
        </plate></config>"""
        numbers = read_plate(a_3mf(header_only))

        assert numbers.print_minutes == 10
        assert not numbers.parsed
