"""Schema truth: the real migrations, against real PostgreSQL.

Everything else in the suite runs on SQLite for speed. This file is where the
schema is actually verified, because Alembic is the only mechanism that will ever
touch a production database (ADR-0008).

Skipped automatically when no PostgreSQL is reachable, so ``pytest`` works with no
Docker. CI always has one, so these never silently stop running there.

Three things are asserted, and the third is the one that matters most:

1. ``upgrade head`` builds the schema from nothing;
2. ``downgrade base`` reverses it — an untested downgrade is not a rollback plan;
3. ``alembic check`` finds no drift, i.e. the migrations and the ORM models agree.
   V1 could not make this assertion at all: it had migrations *and* two hand-written
   schema patchers, so no artefact was authoritative.
"""

from __future__ import annotations

import asyncio
from collections.abc import Iterator
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

from alembic import command
from printorian.core.config import Settings

BACKEND_ROOT = Path(__file__).resolve().parents[1]
TEST_DATABASE = "printorian_migration_test"
EXPECTED_TABLES = {"users", "sessions", "alembic_version"}


def _admin_url() -> str:
    """Sync URL to the maintenance database, derived from configured settings."""
    configured = Settings().database_url
    return configured.replace("+asyncpg", "").rsplit("/", 1)[0] + "/postgres"


def _test_url() -> str:
    configured = Settings().database_url
    return configured.rsplit("/", 1)[0] + "/" + TEST_DATABASE


def _postgres_reachable() -> bool:
    try:
        engine = create_engine(_admin_url(), connect_args={"connect_timeout": 3})
        with engine.connect() as connection:
            connection.execute(text("SELECT 1"))
        engine.dispose()
    except Exception:
        return False
    return True


pytestmark = [
    pytest.mark.db,
    pytest.mark.skipif(
        not _postgres_reachable(),
        reason="no PostgreSQL reachable — run `docker compose up -d`",
    ),
]


@pytest.fixture
def fresh_database() -> Iterator[str]:
    """An empty database, dropped afterwards whatever happens."""
    admin = create_engine(_admin_url(), isolation_level="AUTOCOMMIT")
    with admin.connect() as connection:
        connection.execute(text(f'DROP DATABASE IF EXISTS "{TEST_DATABASE}" WITH (FORCE)'))
        connection.execute(text(f'CREATE DATABASE "{TEST_DATABASE}"'))

    try:
        yield _test_url()
    finally:
        with admin.connect() as connection:
            connection.execute(text(f'DROP DATABASE IF EXISTS "{TEST_DATABASE}" WITH (FORCE)'))
        admin.dispose()


def _alembic_config(url: str) -> Config:
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    config.set_main_option("sqlalchemy.url", url)
    return config


def _table_names(url: str) -> set[str]:
    engine = create_engine(url.replace("+asyncpg", "+psycopg2"), future=True)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_builds_the_schema_from_nothing(fresh_database: str) -> None:
    command.upgrade(_alembic_config(fresh_database), "head")
    assert _table_names(fresh_database) >= EXPECTED_TABLES


def test_downgrade_reverses_the_schema(fresh_database: str) -> None:
    config = _alembic_config(fresh_database)
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    remaining = _table_names(fresh_database)
    assert "users" not in remaining
    assert "sessions" not in remaining


def test_migrations_match_the_orm_models(fresh_database: str) -> None:
    """The gate against schema drift: models and migrations must not diverge."""
    config = _alembic_config(fresh_database)
    command.upgrade(config, "head")

    try:
        command.check(config)
    except AutogenerateDiffsDetected as diff:  # pragma: no cover - failure path
        pytest.fail(f"migrations drifted from the ORM models: {diff}")


def test_single_migration_head(fresh_database: str) -> None:
    """One head, always. Branching migration history is how upgrades start failing."""
    from alembic.script import ScriptDirectory

    script = ScriptDirectory.from_config(_alembic_config(fresh_database))
    assert len(script.get_heads()) == 1


def test_event_loop_is_not_required() -> None:
    """These tests run synchronously; Alembic's env.py owns its own loop."""
    with pytest.raises(RuntimeError):
        asyncio.get_running_loop()
