"""Database access.

One engine, one session factory, one declarative base — and one migration
mechanism (Alembic, ADR-0008). The naming convention below is what makes
autogenerated migrations stable and reviewable instead of noisy.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from datetime import UTC, datetime
from enum import Enum as PyEnum
from typing import Any

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import TypeDecorator

from printorian.core.config import Settings
from printorian.core.ids import EntityId, new_id

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class UtcDateTime(TypeDecorator[datetime]):
    """A timezone-aware timestamp that is always UTC on the way in and out.

    SQLite (used by fast unit tests) drops tzinfo; this restores it so behaviour
    matches Postgres and ``ruff``'s naive-datetime ban stays meaningful.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Any) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError("naive datetime reached the database layer")
        return value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect: Any) -> datetime | None:
        if value is None:
            return None
        return value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)


#: JSON storage (ADR-0017).
#:
#: PostgreSQL's ``json`` type keeps the document as text and reparses it on every
#: access: no GIN index, no containment operator, no key deduplication, and a larger
#: on-disk footprint. ``jsonb`` has none of those problems, and the conversion is a
#: full table rewrite under ``ACCESS EXCLUSIVE`` — so the type has to be right before
#: the rows arrive, not after.
#:
#: Was a ``with_variant`` while the test suite ran on SQLite. It runs on
#: PostgreSQL now (ADR-0021), so the fallback is gone and there is one type here
#: rather than two that could behave differently.
JsonB = postgresql.JSONB()


def enum_column(enum_class: type[PyEnum], *, length: int = 40) -> SAEnum:
    """Persist an enum by value and read it back **as the enum**.

    Declaring these columns as plain ``String`` is a trap: the attribute is typed as
    the enum but SQLAlchemy hands back a bare ``str``, so ``value is Enum.MEMBER`` is
    quietly always False while ``==`` still works. Code that branches on identity
    then takes the wrong path with no error anywhere.

    ``native_enum=False`` keeps it a ``VARCHAR`` rather than a PostgreSQL ``ENUM``
    type, so adding a member is an ordinary migration instead of an ``ALTER TYPE``.

    **These columns carry no database-level CHECK**, and that is a deliberate,
    slightly uncomfortable choice rather than an oversight. SQLAlchemy's
    ``create_constraint`` defaults to ``False``, so turning it on looks like a free
    win — every status column would reject a value outside its enum. It is not free:
    the generated constraint is named after the *enum type*, not the column, so a
    table with two columns of the same enum produces two constraints called the same
    thing. ``order_events`` has exactly that shape — ``from_status`` and
    ``to_status`` are both ``OrderStatus`` — and PostgreSQL refuses the second one,
    so the schema simply fails to build.

    Working around it means passing a hand-picked unique name at every call site,
    which is a rule that holds until somebody adds the thirteenth enum column and
    forgets. The values are validated on write by this type, at the API edge by
    Pydantic, and nothing but application code writes these columns — so the gap is
    narrow. It is recorded here rather than left to be rediscovered.
    """
    return SAEnum(
        enum_class,
        native_enum=False,
        length=length,
        values_callable=lambda members: [member.value for member in members],
    )


class Base(DeclarativeBase):
    """Declarative base for every persistent model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Entity(Base):
    """Common shape for persistent aggregates: UUIDv7 key plus audit timestamps."""

    __abstract__ = True

    id: Mapped[EntityId] = mapped_column(primary_key=True, default=new_id)
    created_at: Mapped[datetime] = mapped_column(
        UtcDateTime, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        UtcDateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )


def _postgres_connect_args(settings: Settings) -> dict[str, Any]:
    """Server-side guards, applied to every connection asyncpg opens.

    Without these one runaway query holds a pooled connection for as long as it
    likes, and a migration blocked behind an idle transaction waits forever rather
    than failing fast and telling somebody. They are set per-connection rather than
    in ``postgresql.conf`` so the application's own limits travel with it — a farm
    that restores onto a fresh box gets them without remembering to.
    """
    return {
        "server_settings": {
            "application_name": "printorian",
            "statement_timeout": str(settings.db_statement_timeout_ms),
            "lock_timeout": str(settings.db_lock_timeout_ms),
            "idle_in_transaction_session_timeout": str(settings.db_idle_in_transaction_timeout_ms),
        }
    }


def create_engine(settings: Settings) -> AsyncEngine:
    """The one engine this process owns.

    Pool sizing is explicit because the default (5 + 10 overflow) is shared by the
    API's request handlers *and* every worker sweep in the same process — the
    telemetry poller alone asks for eight concurrent connections, so the default
    leaves a farm one busy moment away from ``QueuePool limit ... reached``.
    """
    return create_async_engine(
        settings.database_url,
        echo=settings.debug,
        pool_pre_ping=True,
        pool_size=settings.db_pool_size,
        max_overflow=settings.db_max_overflow,
        pool_timeout=settings.db_pool_timeout_seconds,
        # On-prem connections otherwise live for the life of the process, which is
        # fine until a firewall or NAT table quietly drops one and the next borrow
        # fails. Recycling ahead of that turns an outage into a reconnect.
        pool_recycle=settings.db_pool_recycle_seconds,
        connect_args=_postgres_connect_args(settings),
        future=True,
    )


def create_session_factory(engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
    return async_sessionmaker(engine, expire_on_commit=False, autoflush=False)


class Database:
    """Owns the engine and hands out sessions. Constructed once per process."""

    def __init__(self, settings: Settings) -> None:
        self.engine = create_engine(settings)
        self.session_factory = create_session_factory(self.engine)

    async def session(self) -> AsyncIterator[AsyncSession]:
        """Yield a session, committing on success and rolling back on failure."""
        async with self.session_factory() as session:
            try:
                yield session
                await session.commit()
            except Exception:
                await session.rollback()
                raise

    async def dispose(self) -> None:
        await self.engine.dispose()
