"""Database access.

One engine, one session factory, one declarative base — and one migration
mechanism (Alembic, ADR-0008). The naming convention below is what makes
autogenerated migrations stable and reviewable instead of noisy.
"""

from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from datetime import UTC, datetime
from enum import Enum as PyEnum
from typing import Any

from sqlalchemy import CheckConstraint, DateTime, MetaData, func, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import TypeDecorator

from printorian.core.config import Settings
from printorian.core.ids import EntityId, new_id

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class UtcDateTime(TypeDecorator[datetime]):
    """A timezone-aware timestamp that is always UTC on the way in and out.

    SQLite (used by fast unit tests) drops tzinfo; this restores it so behaviour
    matches Postgres and ``ruff``'s naive-datetime ban stays meaningful.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Any) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError("naive datetime reached the database layer")
        return value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect: Any) -> datetime | None:
        if value is None:
            return None
        return value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)


#: JSON storage (ADR-0017).
#:
#: PostgreSQL's ``json`` type keeps the document as text and reparses it on every
#: access: no GIN index, no containment operator, no key deduplication, and a larger
#: on-disk footprint. ``jsonb`` has none of those problems, and the conversion is a
#: full table rewrite under ``ACCESS EXCLUSIVE`` — so the type has to be right before
#: the rows arrive, not after.
#:
#: Was a ``with_variant`` while the test suite ran on SQLite. It runs on
#: PostgreSQL now (ADR-0021), so the fallback is gone and there is one type here
#: rather than two that could behave differently.
JsonB = postgresql.JSONB()


class _CheckedEnum(SAEnum):
    """An ``Enum`` that carries its own CHECK constraint, named after its **column**.

    Two things stop SQLAlchemy's own ``create_constraint=True`` from being enough
    here, and both were why these columns went unchecked until issue #43.

    **The name.** SQLAlchemy names the generated constraint after the enum *type*
    (``Enum.name``, the class name lowercased). Two columns of the same enum on one
    table therefore produce two constraints called the same thing and PostgreSQL
    refuses the second — the schema simply fails to build. ``order_events`` has
    exactly that shape: ``from_status`` and ``to_status`` are both ``OrderStatus``.
    The documented escape is a hand-picked ``name`` at every call site, which is a
    rule that holds until somebody adds the twenty-fourth enum column and forgets.
    The name is derived here instead, from the one thing already unique within a
    table: the column. ``ck_%(table_name)s_%(constraint_name)s`` in
    ``NAMING_CONVENTION`` then turns ``status_enum`` into ``ck_orders_status_enum``.

    **Type-bound constraints are invisible to autogenerate.** Alembic skips any
    CHECK marked ``_type_bound`` on the metadata side, on the assumption that the
    type creates and drops it with the column — so a real constraint in the database
    reads as one the models no longer declare, and every ``alembic check`` reports a
    drop it cannot be talked out of. Migration 0006 hit exactly this and wrote it
    down. Building an ordinary constraint here instead is what makes the two sides
    comparable at all, which is why ``create_constraint`` stays off.

    It buys presence, not contents: Alembic matches CHECK constraints **by name
    only** — measured, not assumed — so a member added to an enum with no migration
    behind it produces no drift and no complaint. `test_migrations` closes that by
    comparing the value sets themselves against the migrated database, and is the
    only thing that does.

    ``_set_table`` is SQLAlchemy's hook for a ``SchemaType`` learning which column it
    was attached to; it runs once per column, before any DDL. If a future SQLAlchemy
    stops calling it the constraints vanish from ``create_all`` and from every
    generated migration — silently, which is why the schema contract test asserts
    one exists for every enum column rather than trusting this to keep working.
    """

    def _set_table(self, column: Any, table: Any) -> None:
        # SQLAlchemy ships no annotations for its schema hooks, so strict mypy reads
        # the base method as untyped. The ignore is on the call, not the file.
        super()._set_table(column, table)  # type: ignore[no-untyped-call]
        CheckConstraint(
            _enum_predicate(column.name, self.enums),
            name=f"{column.name}_enum",
            table=table,
        )


def _enum_predicate(column: str, values: Sequence[str]) -> str:
    """``col IN ('a', 'b')`` as SQL text rather than as a SQLAlchemy expression.

    Text, because that is the form every other CHECK constraint in this schema is
    written in — `__table_args__` is full of them — and a reader comparing a
    migration against a model should not have to translate between two notations.

    Values are enum *values*, so they are source literals and never input; the quote
    doubling is there because it costs nothing and a member with an apostrophe in it
    would otherwise produce a constraint that silently means something else.
    """
    literals = ", ".join("'" + value.replace("'", "''") + "'" for value in values)
    return f"{column} IN ({literals})"


def enum_column(enum_class: type[PyEnum], *, length: int = 40) -> SAEnum:
    """Persist an enum by value, read it back **as the enum**, and CHECK it in the DB.

    Declaring these columns as plain ``String`` is a trap: the attribute is typed as
    the enum but SQLAlchemy hands back a bare ``str``, so ``value is Enum.MEMBER`` is
    quietly always False while ``==`` still works. Code that branches on identity
    then takes the wrong path with no error anywhere.

    ``native_enum=False`` keeps it a ``VARCHAR`` rather than a PostgreSQL ``ENUM``
    type, so adding a member is an ordinary migration instead of an ``ALTER TYPE``.

    The CHECK is what stops that ``VARCHAR`` from meaning "any string". The Python
    type validates on write and Pydantic validates at the edge, but both live in the
    application — a psql session, a data-fix script or an import job reaches the
    column with neither. The constraint is the guard still standing when the writer
    is not application code, which is exactly the case nobody reviews. Its cost is
    that adding a member to an enum now needs a migration to rewrite the constraint,
    and that cost is the point: it is the same review the new value would otherwise
    never get.

    ``create_constraint`` stays off — `_CheckedEnum` builds the constraint itself,
    for reasons that are worth reading before turning it back on.
    """
    return _CheckedEnum(
        enum_class,
        native_enum=False,
        length=length,
        values_callable=lambda members: [member.value for member in members],
    )


class Base(DeclarativeBase):
    """Declarative base for every persistent model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Entity(Base):
    """Common shape for persistent aggregates: UUIDv7 key plus audit timestamps."""

    __abstract__ = True

    id: Mapped[EntityId] = mapped_column(primary_key=True, default=new_id)
    created_at: Mapped[datetime] = mapped_column(
        UtcDateTime, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        UtcDateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )


def _postgres_connect_args(settings: Settings) -> dict[str, Any]:
    """Server-side guards, applied to every connection asyncpg opens.

    Without these one runaway query holds a pooled connection for as long as it
    likes, and a migration blocked behind an idle transaction waits forever rather
    than failing fast and telling somebody. They are set per-connection rather than
    in ``postgresql.conf`` so the application's own limits travel with it — a farm
    that restores onto a fresh box gets them without remembering to.
    """
    return {
        "server_settings": {
            "application_name": "printorian",
            "statement_timeout": str(settings.db_statement_timeout_ms),
            "lock_timeout": str(settings.db_lock_timeout_ms),
            "idle_in_transaction_session_timeout": str(settings.db_idle_in_transaction_timeout_ms),
        }
    }


def create_engine(settings: Settings) -> AsyncEngine:
    """The one engine this process owns.

    Pool sizing is explicit because the default (5 + 10 overflow) is shared by the
    API's request handlers *and* every worker sweep in the same process — the
    telemetry poller alone asks for eight concurrent connections, so the default
    leaves a farm one busy moment away from ``QueuePool limit ... reached``.
    """
    return create_async_engine(
        settings.database_url,
        echo=settings.debug,
        pool_pre_ping=True,
        pool_size=settings.db_pool_size,
        max_overflow=settings.db_max_overflow,
        pool_timeout=settings.db_pool_timeout_seconds,
        # On-prem connections otherwise live for the life of the process, which is
        # fine until a firewall or NAT table quietly drops one and the next borrow
        # fails. Recycling ahead of that turns an outage into a reconnect.
        pool_recycle=settings.db_pool_recycle_seconds,
        connect_args=_postgres_connect_args(settings),
        future=True,
    )


def create_session_factory(engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
    return async_sessionmaker(engine, expire_on_commit=False, autoflush=False)


class Database:
    """Owns the engine and hands out sessions. Constructed once per process."""

    def __init__(self, settings: Settings) -> None:
        self.engine = create_engine(settings)
        self.session_factory = create_session_factory(self.engine)

    async def session(self) -> AsyncIterator[AsyncSession]:
        """Yield a session, committing on success and rolling back on failure."""
        async with self.session_factory() as session:
            try:
                yield session
                await session.commit()
            except Exception:
                await session.rollback()
                raise

    async def dispose(self) -> None:
        await self.engine.dispose()


async def wal_archiving_stalled(session: AsyncSession) -> str | None:
    """The segment WAL archiving is stuck on, or `None` if it is keeping up.

    ADR-0019's whole guarantee rests on archived WAL: without it the recovery
    point is last night's dump rather than the last minute, and `pg_wal` grows
    without bound until it fills the data disk and the farm stops accepting work.

    Both halves of that were reproduced on the first farm host. Filling the backup
    disk broke archiving, `pg_wal` grew, and **every existing signal stayed green**
    — `/health/ready` returned 200, `systemctl --failed` listed nothing, and the
    only evidence was a counter nobody was reading. Worse, the failure did not
    clear when the disk was freed: `archive_command` copies straight to the final
    name, so a part-written segment stays there, `test ! -f` sees it, and archiving
    is wedged until a person deletes the file.

    Compares the two watermarks rather than reading `failed_count`, because that
    counter never resets: a farm that failed once in March would look broken for
    ever, and a check that is permanently red is one people learn to ignore. A
    `last_failed_wal` at or beyond `last_archived_wal` means the *most recent*
    attempt is the one that failed, which is the live condition.
    """
    row = (
        await session.execute(
            text("SELECT last_archived_wal, last_failed_wal FROM pg_stat_archiver")
        )
    ).one_or_none()
    if row is None:
        return None
    return archiving_stalled_on(row[0], row[1])


def archiving_stalled_on(archived: str | None, failed: str | None) -> str | None:
    """The comparison itself, over two watermarks.

    Split out because `pg_stat_archiver` is a server-wide singleton whose contents
    a test cannot arrange: the only way to exercise "failed in March, fine since"
    is to hand the values in. Kept as the single implementation so those tests
    drive the real decision rather than a copy of it — a copy would go on passing
    after this function changed, which is the failure mode that makes a test
    worthless precisely when it is needed.

    WAL segment names are fixed-width uppercase hex, so lexical order is real
    order and `>=` is the right comparison.
    """
    if failed is None:
        return None
    if archived is None or failed >= archived:
        return failed
    return None
