"""Keyset pagination, on the primary key.

Every list endpoint used to return the whole table. That is fine at six printers
and a few hundred orders, and it is an outage at twenty thousand: the order desk
was loading every order ever placed, with every line and every status event
eagerly joined, on each page view.

**Keyset, not ``OFFSET``.** ``OFFSET 10000`` makes PostgreSQL walk and discard ten
thousand rows before returning anything, so the last page of a long list is the
slowest — precisely backwards. A keyset cursor carries the key of the last row seen
and becomes an index seek, so page one thousand costs what page one costs. It also
cannot skip or duplicate a row when something is inserted mid-scroll, which
``OFFSET`` does silently.

**Why the id and not ``created_at``.** The ids are UUIDv7 (`core.ids`): the leading
48 bits are a millisecond timestamp, so they already sort by creation time. Paging
on the primary key therefore gives newest-first ordering *and* an index-only seek
on the key every table already has — no second column, no tiebreaker, no extra
index.

Ordering on ``created_at`` instead looked equivalent and is not. That column is a
server default, so its value comes from the database's clock rather than the
injected one, and its resolution is whatever the dialect offers: SQLite's
``CURRENT_TIMESTAMP`` has *second* granularity and stores the result as text, so a
row written in the same second as the cursor compared as strictly less than it —
every row matched, every page was page one, and the paginator looped forever. That
is a test-dialect artifact, but the lesson is not: a sort key that is unique, is
generated by the application, and needs no tiebreaker is simply a better key. The
one thing given up is that UUIDv7 only orders to the millisecond, so two rows
written in the same millisecond may sort by their random bits — which is still a
*stable total order*, and that is all paging requires.

**The same key is the tiebreak for every other sort.** A query ordered on a
timestamp alone has no total order, so the planner may arrange tied rows either
way — and does: CI and a dev machine disagreed about two ``settings_changes`` rows
ordered by ``changed_at DESC`` and nothing else. Ties are neither rare nor a test
artifact. ``Entity.created_at`` is a ``server_default`` of ``now()``, and in
PostgreSQL ``now()`` is the *transaction's* start, so every row one pass writes —
a planning batch, an order's jobs, a payment and its note — carries a timestamp
identical to the last digit. Under ``FixedClock`` an application-set timestamp
ties for the whole test.

So: **order by the time column, then by ``id``.** The extra term costs nothing and
settles the tie *correctly* rather than merely consistently, because the key is a
UUIDv7 built from the real clock — it stays chronological where the timestamp is
frozen or shared.

**Except in an event log.** UUIDv7 orders only to the millisecond, and a job can
pass through three statuses inside one, so ``JobEvent`` and ``OrderEvent`` carry an
explicit ``sequence`` and *that* is their second term. Where the order of two rows
within a millisecond is load-bearing, a column has to say it; a key cannot.

**Where it is worth the term, and where it is churn.** A sort under a ``LIMIT`` — or
one feeding ``.first()``, a batch, or a count — decides *membership*: a tie at the
boundary moves rows in and out of the answer, so the same data yields different
numbers on different reads. Give those a tiebreak. A sort that returns the whole set
for a screen to render decides only *presentation*: a tie swaps two adjacent rows and
changes nothing computed, and adding a term there is the churn this note is not
asking for. The sites that were read and deliberately left single-term say so where
they sit.

**Two listings are still unpaged, and the farm now measures when that stops being
safe.** ``fleet.table()`` and the materials listing return everything
(`DATABASE-REVIEW` §9): both are bounded by the size of the farm rather than by
history — tens of printers, hundreds of material specs — so an unbounded query there
returns a bounded result, and paging them today would be machinery guarding nothing.

That argument has an expiry date, and the growth that ends it does not arrive as
traffic. It arrives as a *feature*: the purchasing screen adds spare parts,
packaging and printers to the same listing, and the row count changes character on
the day it ships — when nobody is looking at row counts. So
:data:`UNPAGINATED_ROW_TRIGGER`, :func:`capped_count` and :func:`capped_size` are
here rather than a note asking someone to remember. Each context takes its own
reading, because the predicate belongs to the context and a copy of it kept
elsewhere would drift from the listing it claims to measure; `/health/ready` reports
the verdict, which is the treatment `assignment_records` already gets and for the
same reason.
"""

from __future__ import annotations

import binascii
from dataclasses import dataclass
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.orm import InstrumentedAttribute
from sqlalchemy.sql import Select

from printorian.core.errors import ValidationError
from printorian.core.ids import EntityId

#: Rows per page when a caller does not say. Large enough that the console's tables
#: look full, small enough that no single response can carry a whole year.
DEFAULT_PAGE_SIZE = 50

#: The most any caller may ask for. A client asking for a million rows gets two
#: hundred, rather than the server obligingly trying.
MAX_PAGE_SIZE = 200

#: The size at which a listing that returns everything has outgrown that decision.
#:
#: "A few hundred rows", from the deferral argument in `DATABASE-REVIEW` §9, read as
#: 500. It is deliberately not derived from :data:`MAX_PAGE_SIZE`: that is a ceiling
#: on what a *client* may ask for, and this is the point at which nobody should be
#: asking for the whole thing at all. Tying them would make raising one silently
#: move the other.
UNPAGINATED_ROW_TRIGGER = 500


@dataclass(frozen=True, slots=True)
class Cursor:
    """The key of the last row on the previous page."""

    id: EntityId

    def encode(self) -> str:
        """An opaque token.

        Hex of the raw key — opaque so that clients treat it as a token rather than
        reading it and depending on the sort key, which would freeze the ordering
        into every consumer.
        """
        return self.id.hex

    @classmethod
    def decode(cls, token: str) -> Cursor:
        try:
            return cls(id=EntityId(hex=token))
        except (ValueError, AttributeError, TypeError, binascii.Error) as exc:
            # A cursor is generated by this server; a malformed one means the client
            # invented it. Refuse rather than silently starting from the top, which
            # would look like a working paginator quietly repeating page one.
            raise ValidationError("error.pagination.invalid_cursor") from exc


@dataclass(frozen=True, slots=True)
class Page:
    """One page of rows, and where to continue from."""

    rows: list[Any]
    next_cursor: str | None

    @property
    def has_more(self) -> bool:
        return self.next_cursor is not None


def clamp(limit: int | None) -> int:
    """The page size actually used."""
    if limit is None:
        return DEFAULT_PAGE_SIZE
    if limit < 1:
        raise ValidationError("error.pagination.invalid_limit", limit=limit)
    return min(limit, MAX_PAGE_SIZE)


def newest_first(
    query: Select[Any], id_column: InstrumentedAttribute[Any], *, limit: int
) -> Select[Any]:
    """Order newest-first and over-fetch by one.

    The extra row is never returned; its only job is to answer "is there more?"
    without a second ``COUNT``, and to stop the last full page from advertising an
    empty page after it.
    """
    return query.order_by(id_column.desc()).limit(limit + 1)


def after(
    query: Select[Any], cursor: Cursor | None, *, id_column: InstrumentedAttribute[Any]
) -> Select[Any]:
    """Restrict ``query`` to rows strictly after ``cursor`` in newest-first order."""
    if cursor is None:
        return query
    return query.where(id_column < cursor.id)


@dataclass(frozen=True, slots=True)
class ListingSize:
    """How many objects a listing that returns everything would serialise.

    ``rows`` **saturates**. Counting stops at :data:`UNPAGINATED_ROW_TRIGGER`, so a
    reading that reached the trigger is a *floor* rather than a measurement, and
    ``is_exact`` is what says which of the two it is. A capped count presented as an
    exact one would be a number the farm did not measure (root CLAUDE.md §1) — and
    note which direction it errs in: the figure can only ever understate, and it
    understates only by stopping at the line. So the verdict it feeds stays correct
    either way; it is the figure printed beside the verdict that stops being a
    measurement, and that is the part that has to say so.
    """

    listing: str
    rows: int
    is_exact: bool

    @property
    def past_trigger(self) -> bool:
        """Whether this listing has reached the size at which it should be paged."""
        return self.rows >= UNPAGINATED_ROW_TRIGGER


def capped_count(query: Select[Any]) -> Select[Any]:
    """Count what ``query`` matches, reading no more than the trigger.

    ``SELECT count(*) FROM (<query> LIMIT trigger)`` — bounded by construction, and
    that is the whole point of it. This runs on ``/health/ready``, which a container
    runtime probes every few seconds, and a plain ``count(*)`` would be a scan that
    grows at exactly the rate of the problem it is watching: the check would get
    slower the more it had to say, and would be at its most expensive on the farm
    that most needed the answer. `contexts.production.growth` refuses ``count(*)``
    on the same path for the same reason and reaches for the catalogue instead;
    that escape is not available here, because these readings have a *predicate* —
    active specs, lots with material left in them — and ``pg_class`` counts whole
    relations or nothing.

    The price is that the answer stops being a number once it is over the line,
    which :class:`ListingSize` carries honestly rather than rounding away.
    """
    return select(func.count()).select_from(query.limit(UNPAGINATED_ROW_TRIGGER).subquery())


def capped_size(listing: str, *counts: int) -> ListingSize:
    """One reading, from the capped counts that make it up.

    A listing may serialise more than one kind of row — the materials table nests
    each spec's lots inside it, so the response grows on two axes and either one
    alone can be what makes it too big. Each part is counted and capped separately,
    so any part that reached its cap makes the total a floor, and the reading says
    so.

    Summing capped parts cannot produce a false "fine": a part only saturates by
    reaching the trigger, which on its own puts the total past it.
    """
    return ListingSize(
        listing=listing,
        rows=sum(counts),
        is_exact=all(count < UNPAGINATED_ROW_TRIGGER for count in counts),
    )


def paginate(rows: list[Any], limit: int) -> Page:
    """Split an over-fetched result into a page and its continuation token."""
    if len(rows) <= limit:
        return Page(rows=rows, next_cursor=None)

    page = rows[:limit]
    return Page(rows=page, next_cursor=Cursor(id=page[-1].id).encode())


__all__ = [
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "UNPAGINATED_ROW_TRIGGER",
    "Cursor",
    "ListingSize",
    "Page",
    "after",
    "capped_count",
    "capped_size",
    "clamp",
    "newest_first",
    "paginate",
]
