"""Keyset pagination, on the primary key.

Every list endpoint used to return the whole table. That is fine at six printers
and a few hundred orders, and it is an outage at twenty thousand: the order desk
was loading every order ever placed, with every line and every status event
eagerly joined, on each page view.

**Keyset, not ``OFFSET``.** ``OFFSET 10000`` makes PostgreSQL walk and discard ten
thousand rows before returning anything, so the last page of a long list is the
slowest — precisely backwards. A keyset cursor carries the key of the last row seen
and becomes an index seek, so page one thousand costs what page one costs. It also
cannot skip or duplicate a row when something is inserted mid-scroll, which
``OFFSET`` does silently.

**Why the id and not ``created_at``.** The ids are UUIDv7 (`core.ids`): the leading
48 bits are a millisecond timestamp, so they already sort by creation time. Paging
on the primary key therefore gives newest-first ordering *and* an index-only seek
on the key every table already has — no second column, no tiebreaker, no extra
index.

Ordering on ``created_at`` instead looked equivalent and is not. That column is a
server default, so its value comes from the database's clock rather than the
injected one, and its resolution is whatever the dialect offers: SQLite's
``CURRENT_TIMESTAMP`` has *second* granularity and stores the result as text, so a
row written in the same second as the cursor compared as strictly less than it —
every row matched, every page was page one, and the paginator looped forever. That
is a test-dialect artifact, but the lesson is not: a sort key that is unique, is
generated by the application, and needs no tiebreaker is simply a better key. The
one thing given up is that UUIDv7 only orders to the millisecond, so two rows
written in the same millisecond may sort by their random bits — which is still a
*stable total order*, and that is all paging requires.
"""

from __future__ import annotations

import binascii
from dataclasses import dataclass
from typing import Any

from sqlalchemy.orm import InstrumentedAttribute
from sqlalchemy.sql import Select

from printorian.core.errors import ValidationError
from printorian.core.ids import EntityId

#: Rows per page when a caller does not say. Large enough that the console's tables
#: look full, small enough that no single response can carry a whole year.
DEFAULT_PAGE_SIZE = 50

#: The most any caller may ask for. A client asking for a million rows gets two
#: hundred, rather than the server obligingly trying.
MAX_PAGE_SIZE = 200


@dataclass(frozen=True, slots=True)
class Cursor:
    """The key of the last row on the previous page."""

    id: EntityId

    def encode(self) -> str:
        """An opaque token.

        Hex of the raw key — opaque so that clients treat it as a token rather than
        reading it and depending on the sort key, which would freeze the ordering
        into every consumer.
        """
        return self.id.hex

    @classmethod
    def decode(cls, token: str) -> Cursor:
        try:
            return cls(id=EntityId(hex=token))
        except (ValueError, AttributeError, TypeError, binascii.Error) as exc:
            # A cursor is generated by this server; a malformed one means the client
            # invented it. Refuse rather than silently starting from the top, which
            # would look like a working paginator quietly repeating page one.
            raise ValidationError("error.pagination.invalid_cursor") from exc


@dataclass(frozen=True, slots=True)
class Page:
    """One page of rows, and where to continue from."""

    rows: list[Any]
    next_cursor: str | None

    @property
    def has_more(self) -> bool:
        return self.next_cursor is not None


def clamp(limit: int | None) -> int:
    """The page size actually used."""
    if limit is None:
        return DEFAULT_PAGE_SIZE
    if limit < 1:
        raise ValidationError("error.pagination.invalid_limit", limit=limit)
    return min(limit, MAX_PAGE_SIZE)


def newest_first(
    query: Select[Any], id_column: InstrumentedAttribute[Any], *, limit: int
) -> Select[Any]:
    """Order newest-first and over-fetch by one.

    The extra row is never returned; its only job is to answer "is there more?"
    without a second ``COUNT``, and to stop the last full page from advertising an
    empty page after it.
    """
    return query.order_by(id_column.desc()).limit(limit + 1)


def after(
    query: Select[Any], cursor: Cursor | None, *, id_column: InstrumentedAttribute[Any]
) -> Select[Any]:
    """Restrict ``query`` to rows strictly after ``cursor`` in newest-first order."""
    if cursor is None:
        return query
    return query.where(id_column < cursor.id)


def paginate(rows: list[Any], limit: int) -> Page:
    """Split an over-fetched result into a page and its continuation token."""
    if len(rows) <= limit:
        return Page(rows=rows, next_cursor=None)

    page = rows[:limit]
    return Page(rows=page, next_cursor=Cursor(id=page[-1].id).encode())


__all__ = [
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "Cursor",
    "Page",
    "after",
    "clamp",
    "newest_first",
    "paginate",
]
