"""the settings store, and the record of who changed what

About a hundred farm parameters live in code today — `pricing/rates.py` and
`core/config.py` — so changing a labour rate or a margin means a redeploy. For a
product that ships to somebody else's building that is closer to a defect than a
gap, and it is the thing four of the five unbuilt kit screens are waiting on
(`docs/DESIGN-KIT.md` §2.1).

**Key/value, because a column per setting means a migration per setting.** They
are heterogeneous and the set grows; `contexts/settings/catalogue.py` does the
type-checking the database cannot, deriving keys and defaults from
`dataclasses.fields(RateSnapshot)` so the next rate somebody adds appears without
a second place to remember.

**Nothing is seeded, and that is the safety property.** A key with no row resolves
to the code default it always had, so this migration changes no farm's prices on
the day it runs, and `downgrade` is lossless in the only sense that matters — the
farm returns to the behaviour it has now.

The audit is not optional: «Было · Стало» is what lets an owner answer *why did
the price change last Tuesday*, which is the question the screen exists for. It
outlives the setting — resetting a rate keeps the history of it.

Revision ID: 0018_settings
Revises: 0017_metric_rollups
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0018_settings"
down_revision: str | None = "0017_metric_rollups"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "settings_audit",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_settings_audit_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings_audit")),
    )
    op.create_index("ix_settings_audit_changed_at", "settings_audit", ["changed_at"], unique=False)
    op.create_index(
        "ix_settings_audit_key_changed_at", "settings_audit", ["key", "changed_at"], unique=False
    )
    # Both foreign keys are `ON DELETE SET NULL`, so deleting a user touches every
    # row of both tables. `tests/test_schema_contracts.py` requires an index
    # leading on every foreign key for exactly that reason.
    op.create_index("ix_settings_updated_by", "settings", ["updated_by"], unique=False)
    op.create_index("ix_settings_audit_changed_by", "settings_audit", ["changed_by"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_settings_audit_changed_by", table_name="settings_audit")
    op.drop_index("ix_settings_updated_by", table_name="settings")
    op.drop_index("ix_settings_audit_key_changed_at", table_name="settings_audit")
    op.drop_index("ix_settings_audit_changed_at", table_name="settings_audit")
    op.drop_table("settings_audit")
    op.drop_table("settings")
    # ### end Alembic commands ###
