"""prepared plates and estimate variance

Revision ID: 21c394b4d2f0
Revises: 9aa1e5de8d6c
Created: 2026-08-08 18:49:09.059794
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "21c394b4d2f0"
down_revision: str | None = "9aa1e5de8d6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prepared_plates",
        sa.Column("plate_key", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("valid", "stale", "rejected", name="platestatus", native_enum=False, length=40),
            nullable=False,
        ),
        sa.Column("model_hash", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=300), nullable=False),
        sa.Column("scale", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("material_code", sa.String(length=80), nullable=False),
        sa.Column("printer_profile", sa.String(length=120), nullable=False),
        sa.Column("layout_hash", sa.String(length=64), nullable=False),
        sa.Column("print_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("filament_grams", sa.JSON(), nullable=False),
        sa.Column("layer_count", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("sliced_by", sa.Uuid(), nullable=True),
        sa.Column("sliced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("slicer_name", sa.String(length=80), nullable=False),
        sa.Column("slicer_version", sa.String(length=40), nullable=False),
        sa.Column("profile_version", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prepared_plates")),
        sa.UniqueConstraint("plate_key", name="uq_prepared_plates_key"),
    )
    op.create_index(
        op.f("ix_prepared_plates_plate_key"), "prepared_plates", ["plate_key"], unique=False
    )
    op.create_table(
        "estimate_variances",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("quoted_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("prepared_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tolerance", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("within_tolerance", sa.Boolean(), nullable=False),
        sa.Column("estimated_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("prepared_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("estimated_grams", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("prepared_grams", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["print_jobs.id"],
            name=op.f("fk_estimate_variances_job_id_print_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_estimate_variances_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimate_variances")),
    )
    op.create_index("ix_estimate_variances_job_id", "estimate_variances", ["job_id"], unique=False)
    op.add_column("print_jobs", sa.Column("prepared_plate_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_print_jobs_prepared_plate_id_prepared_plates"),
        "print_jobs",
        "prepared_plates",
        ["prepared_plate_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_print_jobs_prepared_plate_id_prepared_plates"), "print_jobs", type_="foreignkey"
    )
    op.drop_column("print_jobs", "prepared_plate_id")
    op.drop_index("ix_estimate_variances_job_id", table_name="estimate_variances")
    op.drop_table("estimate_variances")
    op.drop_index(op.f("ix_prepared_plates_plate_key"), table_name="prepared_plates")
    op.drop_table("prepared_plates")
    # ### end Alembic commands ###
