"""production jobs and scheduling decisions

Revision ID: 9aa1e5de8d6c
Revises: 0004_fleet
Created: 2026-08-08 18:29:44.583648
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9aa1e5de8d6c"
down_revision: str | None = "0004_fleet"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "print_jobs",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ready",
                "assigned",
                "dispatching",
                "printing",
                "succeeded",
                "failed",
                "cancelled",
                name="jobstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("printer_id", sa.Uuid(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("material_type", sa.String(length=80), nullable=False),
        sa.Column("colors", sa.JSON(), nullable=False),
        sa.Column("width_mm", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("depth_mm", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("height_mm", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("nozzle_diameter_mm", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("grams_required", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("estimated_minutes", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("plate_filename", sa.String(length=300), nullable=True),
        sa.Column("remote_path", sa.String(length=500), nullable=True),
        sa.Column("job_handle", sa.String(length=200), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=True),
        sa.Column("failure_code", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_print_jobs_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["printer_id"],
            ["printers.id"],
            name=op.f("fk_print_jobs_printer_id_printers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_print_jobs")),
    )
    op.create_index("ix_print_jobs_order_id", "print_jobs", ["order_id"], unique=False)
    op.create_index("ix_print_jobs_printer_id", "print_jobs", ["printer_id"], unique=False)
    op.create_index(
        "ix_print_jobs_status_created_at", "print_jobs", ["status", "created_at"], unique=False
    )
    op.create_table(
        "assignment_records",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("chosen_printer_id", sa.String(length=64), nullable=True),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("winning_score", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["print_jobs.id"],
            name=op.f("fk_assignment_records_job_id_print_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignment_records")),
    )
    op.create_index(
        "ix_assignment_records_job_id_created_at",
        "assignment_records",
        ["job_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "job_events",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=40), nullable=True),
        sa.Column("to_status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["print_jobs.id"],
            name=op.f("fk_job_events_job_id_print_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
    )
    op.create_table(
        "wait_list_entries",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=False),
        sa.Column("predicted_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocking_reasons", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["print_jobs.id"],
            name=op.f("fk_wait_list_entries_job_id_print_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_wait_list_entries_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wait_list_entries")),
    )
    op.create_index("ix_wait_list_entries_job_id", "wait_list_entries", ["job_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wait_list_entries_job_id", table_name="wait_list_entries")
    op.drop_table("wait_list_entries")
    op.drop_table("job_events")
    op.drop_index("ix_assignment_records_job_id_created_at", table_name="assignment_records")
    op.drop_table("assignment_records")
    op.drop_index("ix_print_jobs_status_created_at", table_name="print_jobs")
    op.drop_index("ix_print_jobs_printer_id", table_name="print_jobs")
    op.drop_index("ix_print_jobs_order_id", table_name="print_jobs")
    op.drop_table("print_jobs")
    # ### end Alembic commands ###
